#  See also: https://packaging.python.org/guides/supporting-windows-using-appveyor/#setting-up

image:
- Visual Studio 2015

environment:
    matrix:
        - PYTHON: "C:\\Python36-x64"
    PATH: "%PATH%;C:\\projects\\mnemosyne\\miktex\\texmfs\\install\\miktex\\bin"
    APPVEYOR_SAVE_CACHE_ON_ERROR: "true"

version: '{branch}-{build}'

platform: x64

clone_depth: 20

build: off

cache:
  - C:\cache -> .appveyor.yml

# Enable rdp connections on init or finish
#init:
    #- ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
#on_finish:
    #- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

install:
    - ps: "If (!(Test-Path C:\\cache)){mkdir C:\\cache}"
    - ps: "If (!(Test-Path C:\\cache\\pip)){mkdir C:\\cache\\pip}"
    - ps: "If (!(Test-Path C:\\cache\\miktex-portable.exe)){wget http://mirrors.ctan.org/systems/win32/miktex/setup/miktex-portable.exe -OutFile C:\\cache\\miktex-portable.exe}"
    - cmd: "7z x C:\\cache\\miktex-portable.exe * -aot -omiktex"
    - cmd: "dir C:\\cache"
      # Not sure why we need it, but dvipng triggers the miktex package manager
      # and wants to install zhmetrics
      # If we ever need a local miktex repository: # https://bruceyf.wordpress.com/2008/05/07/miktexs-secret-local-package-repository/
    - cmd: "mpm --install=zhmetrics"
    - cmd: "latex -interaction=nonstopmode -version"
    - cmd: "%PYTHON%\\python.exe -m pip install --cache-dir C:\\cache\\pip -r requirements.txt"
    - ps: "mkdir -p mo\\de\\LC_MESSAGES"
    - cmd: "%PYTHON%\\python.exe po\\msgfmt.py -o mo\\de\\LC_MESSAGES\\mnemosyne.mo po\\de.po"

test_script:
    # Use -v to list test names
    - cmd: "%PYTHON%\\python.exe -m nose tests"
