sudo: required

language: python

cache: pip

python:
    - "3.5"
    - "3.6"

before_install:
  - if echo "$TRAVIS_COMMIT_MESSAGE" | grep -F -q "[skip travis]" ; then echo "[skip travis] has been found, exiting" && exit 0 ; else echo "[skip travis] has not been found, continuing" ; fi
  - sudo apt-get -qq update && sudo apt-get install -y --no-install-recommends texlive-latex-base dvipng

install:
  - pip install -r requirements.txt
  - if [[ $TRAVIS_PYTHON_VERSION == 3.6 ]]; then
    pip install coverage;
    fi

script:
  - if [[ $TRAVIS_PYTHON_VERSION == 3.6 ]]; then
    make coverage;
    else make test;
    fi

after_success:
  - if [[ $TRAVIS_PYTHON_VERSION == 3.6 ]]; then
    pip install codecov;
    codecov;
    fi
